const types = {
   SET_STATUS: "SET_STATUS",
   SET_USER: "SET_USER",
   REVOKE_USER: "REVOKE_USER",
   LOAD_USER: "LOAD_USER",
   SET_STORIES_FEED: "SET_STORIES_FEED",
   UPDATE_STORIES_FEED: "UPDATE_STORIES_FEED",
   SET_CURRENT_STORY: "SET_CURRENT_STORY",
   SET_CURRENT_USER: "SET_CURRENT_USER",
   SET_MORE_USER_DATA: "SET_MORE_USER_DATA",
   SET_MORE_STORIES_FROM_USER: "SET_MORE_STORIES_FROM_USER",
   SHOW_TOAST: "SHOW_TOAST",
   DISMISS_TOAST: "DISMISS_TOAST",
   TOGGLE_MODAL: "TOGGLE_MODAL",
   SET_MODAL_COMPONENT: "SET_MODAL_COMPONENT"
}

export default types;