export default {
   SET_STATUS: "SET_STATUS",
   SET_USER: "SET_USER",
   REVOKE_USER: "REVOKE_USER",
   LOAD_USER: "LOAD_USER",
   TOGGLE_MODAL: "TOGGLE_MODAL",
   SHOW_TOAST: "SHOW_TOAST",
   DISMISS_TOAST: "DISMISS_TOAST",
   SET_MODAL_COMPONENT: "SET_MODAL_COMPONENT"
}